[package]
name = "ncrs"
description = "Netcat, but in Rust"
version = "0.1.0"
authors = ["interrrp <int@addictedto.coffee"]
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
